### ISSUE TITLE
Use of templates

### ISSUE THREAD

**Issue by titansmc** [e-user/50shades#1]
Hi,
I don't manage to get the templates working... Could you elaborate a bit more on this? I ha trying to get a template that shows the logs for haproxy instances and it looks like:

```
haproxy = '[{{default source "haproxy01.domain.com"}}] {{message}}'
```
So I need logs where source:haproxy01.domain.com
Is it also possible to use them without having to define them in config.toml? 

Cheers.

**Comment by outergod** [comment]
Hi!

Templates control the output, only. Your example would check the `source` field and write its value, or `haproxy01.domain.com` if it isn't set.

Query parameters are simply appended to the invocation, which is also documented for both `query` and `follow`:

```
50shades query [OPTIONS] [QUERY]...
50shades follow [OPTIONS] [QUERY]...
```

So in order to filter for `source:haproxy01.domain.com`, you would invoke

```
50shades query source:haproxy01.domain.com
50shades follow source:haproxy01.domain.com
```

 respectively. Does that fix your problem?

**Comment by titansmc** [comment]
Sorry, you are right...
Thanks.
